bundled_packages_dir: packages
data_dir: data
description: LLaMa-7B language model for text generation
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  pretty_name: LLaMa 7B
  tags:
  - text-generation
model_module_dir: model
model_name: LLaMa 7B
model_type: custom
python_version: py38
requirements:
- torch
- peft
- sentencepiece
- git+https://github.com/huggingface/transformers.git
resources:
  cpu: "3"
  memory: 14Gi
  use_gpu: true
  accelerator: A10G
secrets: {}
spec_version: '2.0'
system_packages: []
external_data:
  - url: https://baseten-public.s3.us-west-2.amazonaws.com/models/llama/pytorch_model-00001-of-00002.bin
    local_data_path: pytorch_model-00001-of-00002.bin
  - url: https://baseten-public.s3.us-west-2.amazonaws.com/models/llama/pytorch_model-00002-of-00002.bin
    local_data_path: pytorch_model-00002-of-00002.bin
